### ISSUE TITLE
Usage instructions?

### ISSUE THREAD

**Issue by aaronjanse** [Sorunome/mx-puppet-instagram#18]
Thanks for creating this!

I've got a DM with the bot, but I'm having trouble bridging rooms. It seems like both `listusers` and `listrooms` are unimplemented. The output of `help` also doesn't show a `bridge` command. Am I doing something wrong?

**Comment by Sorunome** [comment]
Nope, you're not doing anything wrong. after running `link username password` you have to wait until someone messages you

**Comment by aaronjanse** [comment]
Whoa! Perfect.

Thanks for the quick response, and for writing all these bridges! Your code will have a positive effect on my day-to-day life as I'm chatting with friends across many platforms :-)
