### ISSUE TITLE
where to get setmatrixtoken

### ISSUE THREAD

**Issue by luxus** [Sorunome/mx-puppet-instagram#22]
I thought it is the token I can get from the about screen
but when I try `setmatrixtoken` with that long string I get
`ERROR: Invalid matrix token`

**Comment by leporia** [comment]
I think the token is correct but the request uses the wrong url
```
Jan-22 13:47:18.018 [BotProvisioner] info: Got message to process with arg=setmatrixtoken
Jan-22 13:47:18.041 [bot-sdk-MatrixLiteClient] info: (REQ-1) GET https://example.com/_matrix/client/r0/account/whoami
Jan-22 13:47:18.059 [bot-sdk-MatrixLiteClient] error: (REQ-1) <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>
```
I get this error in the logs.
I think the `GET https://example.com` should be `GET http://localhost:8008`, it seems that it takes the key `domain` instead of the key `homeserverUrl` from the config file or maybe I forgot to set something in the config.

**Comment by luxus** [comment]
thanks for the research

**Comment by Sorunome** [comment]
you gotta set up client well-known on your homeserver for it to work properly

22. 1. 2021 15:12:56 leporia <notifications@github.com>:

**Comment by leporia** [comment]
Oh, I've missed that. Thanks! Now it works.

For anyone searching how to do it: https://matrix.org/docs/spec/client_server/latest#get-well-known-matrix-client

**Comment by luxus** [comment]
confirmed.. well-known must work, now I can set the token
