### ISSUE TITLE
Add suffix to the display name

### ISSUE THREAD

**Issue by leporia** [Sorunome/mx-puppet-instagram#24]
It works well but sometimes I cannot understand if a user is from the Instagram puppet or not. I suggest adding something like "(IG)" at the end of the display name.

**Comment by Sorunome** [comment]
You can configure that with name patterns https://github.com/Sorunome/mx-puppet-bridge/blob/master/sample.config.yaml#L133

For example,

```yaml
namePatterns:
  user: :name (IG)
```
