### ISSUE TITLE
Add Instagram identifier to usernames

### ISSUE THREAD

**Issue by rsre** [Sorunome/mx-puppet-instagram#25]
In other bridges when you import the users from other chat service a string is attached to their names to show where they come from. For example, if I talk to Sorunome from Instagram it would show as "Sorunome (Instagram)".

Would it be possible to add this feature?

I'm not very familiar with Typescript or your library, but I've been looking at the source and maybe it could be added at line 67 of instagram.ts, something like:
`
name: user.name + ' (Instagram)',
`

If you can confirm that makes sense I can create a Pull Request.

Have a nice day :)

**Comment by Sorunome** [comment]
you can already do that with the name patterns blovk in your config.yaml

14. 2. 2021 22:53:37 Ricardo <notifications@github.com>:

**Comment by rsre** [comment]
I've tried to edit this part like this:
`
namePatterns:
  # Override the protocols set default name patterns
  # Which variables are available depends on protocol implementation
  user: :name + ' (Instagram)'
  userOverride: :name + ' (Instagram)'
  room: :name
  group: :name
`

but it doesn't seem to have the effect I'm hoping for... Can you point me to some further documentation about how to properly configure this?
